export const packageName = "@workforce/desktop-client" as const;

export { createDesktopClient, DesktopClient } from "./client.js";
export type { DesktopClientOptions } from "./client.js";
export { ProblemError, isProblemDetails } from "./errors.js";
export { assertSafePath, paths } from "./paths.js";
export { createLoopbackTransport } from "./transport.js";
export type {
  ClientTransport,
  LoopbackTransportOptions,
  TransportRequest,
  TransportResponse,
} from "./transport.js";
export type {
  ApprovalDecisionInput,
  ApprovalDto,
  ArtifactDto,
  ArtifactLineageDto,
  ArtifactVersionDto,
  ArtifactVersionSummaryDto,
  AuthoringChatProposalDto,
  AuthoringSessionListQuery,
  AuthoringSessionPageDto,
  AuthoringSessionSummaryDto,
  AuthoringSessionViewDto,
  AuthoringTurnActionAcceptedDto,
  AuthoringTurnDto,
  CancelInput,
  CapabilitiesDto,
  CommandAcceptedDto,
  CommandOptions,
  ConfirmPlanInput,
  AppendAuthoringSessionMessageInput,
  AuthoringDraftDto,
  AuthoringSessionDto,
  AuthoringSessionMessageDto,
  CreateAuthoringSessionInput,
  CreateProjectInput,
  CreateTeamInput,
  CreateTeamVersionInput,
  CreateWorkflowInput,
  CreateWorkflowVersionInput,
  CreateWorkerInput,
  ChatClassifyInput,
  ChatClassifyResultDto,
  CreateWorkspaceInput,
  EventListQuery,
  ExportBundleDto,
  ForkWorkerVersionAcceptedDto,
  HealthDto,
  ListQuery,
  ListWorkersInput,
  NodeDto,
  OperationDto,
  PageDto,
  PatchProjectInput,
  PatchTeamInput,
  PatchTeamVersionInput,
  PatchWorkflowInput,
  PatchWorkflowVersionInput,
  PatchWorkerInput,
  ProblemDetails,
  ProjectBudgetDto,
  ProjectDto,
  ProjectProgressProjectionDto,
  ReadyDto,
  RunDto,
  RunInputBody,
  RuntimeCapabilitiesDto,
  RuntimeCapabilityItemDto,
  RuntimeDto,
  SendAuthoringMessageAcceptedDto,
  SessionDto,
  StartProjectInput,
  StartTaskRunInput,
  TaskDependency,
  TaskDto,
  TeamDto,
  TeamMemberDto,
  TeamRoleDto,
  TeamVersionDto,
  VersionDto,
  WorkerCardFieldName,
  WorkerCardFieldsDto,
  WorkerDraftDto,
  WorkerDraftWrite,
  WorkerDto,
  WorkerPageDto,
  WorkerVersionDto,
  WorkerVersionReferencesDto,
  WorkflowDto,
  WorkflowGraphEdgeDto,
  WorkflowGraphNodeDto,
  WorkflowStepDto,
  WorkflowVersionDto,
  WorkspaceDto,
} from "./types.js";
