export const packageName = "@workforce/desktop-client" as const;

export { createDesktopClient, DesktopClient } from "./client.js";
export type { DesktopClientOptions } from "./client.js";
export { ProblemError, isProblemDetails } from "./errors.js";
export { assertSafePath, paths } from "./paths.js";
export { createLoopbackTransport } from "./transport.js";
export type {
  ClientTransport,
  LoopbackTransportOptions,
  TransportRequest,
  TransportResponse,
} from "./transport.js";
export type {
  ApprovalDecisionInput,
  ApprovalDto,
  ArtifactDto,
  ArtifactLineageDto,
  ArtifactVersionDto,
  ArtifactVersionSummaryDto,
  CancelInput,
  CapabilitiesDto,
  CommandAcceptedDto,
  CommandOptions,
  ConfirmPlanInput,
  CreateProjectInput,
  CreateTeamInput,
  CreateTeamVersionInput,
  CreateWorkspaceInput,
  EventListQuery,
  ExportBundleDto,
  HealthDto,
  ListQuery,
  NodeDto,
  OperationDto,
  PageDto,
  PatchProjectInput,
  PatchTeamInput,
  PatchTeamVersionInput,
  ProblemDetails,
  ProjectBudgetDto,
  ProjectDto,
  ReadyDto,
  RunDto,
  RunInputBody,
  RuntimeCapabilitiesDto,
  RuntimeCapabilityItemDto,
  RuntimeDto,
  SessionDto,
  StartProjectInput,
  TaskDependency,
  TaskDto,
  TeamDto,
  TeamMemberDto,
  TeamRoleDto,
  TeamVersionDto,
  VersionDto,
  WorkflowDto,
  WorkflowGraphEdgeDto,
  WorkflowGraphNodeDto,
  WorkflowStepDto,
  WorkflowVersionDto,
  WorkspaceDto,
  CreateTeamInput,
  CreateTeamVersionInput,
  CreateWorkflowInput,
  CreateWorkflowVersionInput,
  PatchTeamInput,
  PatchTeamVersionInput,
  PatchWorkflowInput,
  PatchWorkflowVersionInput,
} from "./types.js";
